services:
  - type: web
    name: stock-radar-webhook
    runtime: python
    envVars:
      - key: TG_TOKEN
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
