services:
  - type: web                     # 保持 Web Service
    name: stock-radar-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_stub.py     # ← 指向新檔
    envVars:
      - key: TG_TOKEN
        sync: false            # 在 Render GUI 填 token
