services:
  - type: worker                 # ← 原本是 web
    name: stock-radar-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TG_TOKEN            # 在 GUI 填實際 Token
        sync: false
